version: "3"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: a1add53c-f843-4eb1-b41d-6a32d6fd4404
  keycloak:
    image: quay.io/keycloak/keycloak
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: a1add53c-f843-4eb1-b41d-6a32d6fd4404
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: a76b13ad-5662-4c69-aef0-6976eaf62225
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    ports:
      - 8080:8080
    depends_on:
      - postgres